name: dsw-server
version: '1.9.1'
synopsis: DSW Server
description: DSW Server
category: Web
author: Vojtech Knaisl <vknaisl@gmail.com>
maintainer: Vojtech Knaisl <vknaisl@gmail.com>
copyright: 2019 Vojtech Knaisl <vknaisl@gmail.com>
license: Apache
license-file: LICENSE.md
homepage: https://github.com/ds-wizard/dsw-server
git: git@github.com:ds-wizard/dsw-server.git
bug-reports: https://github.com/ds-wizard/ds-wizard/issues
tested-with: GHC==8.6.*
data-files:
  - config/application.yml
  - config/build-info.yml
  - templates/dmp/root.css
  - templates/dmp/root.html.j2
  - templates/mail/_common/images/logo.png
  - templates/mail/_common/footer.txt.j2
  - templates/mail/_common/layout.html.j2
  - templates/mail/_common/style.css
  - templates/mail/registrationConfirmation/message.html.j2
  - templates/mail/registrationConfirmation/message.txt.j2
  - templates/mail/registrationCreatedAnalytics/message.html.j2
  - templates/mail/registrationCreatedAnalytics/message.txt.j2
  - templates/mail/resetPassword/message.html.j2
  - templates/mail/resetPassword/message.txt.j2
library:
  source-dirs: lib
  when:
  - condition: os(darwin)
    then:
      ghc-options: -j +RTS -A256m -n4m -RTS -j8 -O0 -dynamic -fwarn-unused-imports -fno-warn-warnings-deprecations
    else:
      ghc-options: -fwarn-unused-imports -fno-warn-warnings-deprecations
  dependencies:
  - base
  - aeson
  - amqp
  - blaze-html
  - bson
  - bson-generic
  - bytestring
  - case-insensitive
  - containers
  - data-default
  - directory
  - dsw-metamodel-migrator
  - exceptions
  - filepath
  - fromhtml
  - ginger
  - github
  - hashable
  - HaskellNet
  - HaskellNet-SSL
  - http-client
  - http-client-tls
  - http-types
  - jwt
  - lens
  - lens-aeson
  - markdown
  - mime-mail
  - mime-types
  - MissingH
  - mtl
  - monad-control
  - monad-logger
  - mongoDB
  - mongoDB-migration
  - network
  - persistent
  - persistent-mongoDB
  - persistent-template
  - pretty-simple
  - pretty-terminal
  - pwstore-fast
  - random
  - regex-compat
  - retry
  - roman-numerals
  - scotty
  - text
  - text-replace
  - time
  - transformers
  - unordered-containers
  - uri-encode
  - uuid
  - vector
  - wai
  - wai-extra
  - wai-cors
  - warp
  - wreq
  - yaml
  default-extensions:
    - TemplateHaskell
    - QuasiQuotes
    - OverloadedStrings
    - MultiParamTypeClasses
    - FlexibleContexts
    - GeneralizedNewtypeDeriving
    - GADTs
    - TypeFamilies
    - DeriveGeneric
    - ExtendedDefaultRules
    - RecordWildCards
    - UnicodeSyntax
    - ExistentialQuantification
    - FunctionalDependencies
    - TypeSynonymInstances
    - FlexibleInstances
    - ScopedTypeVariables
    - RankNTypes

executables:
  dsw-server:
    main: Main.hs
    source-dirs: app
    when:
    - condition: os(darwin)
      then:
        ghc-options: -j +RTS -A256m -n4m -RTS -j8 -O0 -dynamic -fwarn-unused-imports -fno-warn-warnings-deprecations
      else:
        ghc-options: -fwarn-unused-imports -fno-warn-warnings-deprecations
    dependencies:
    - base
    - dsw-server
tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    when:
    - condition: os(darwin)
      then:
        ghc-options: -j +RTS -A256m -n4m -RTS -j8 -O0 -dynamic -fwarn-unused-imports -fno-warn-warnings-deprecations
      else:
        ghc-options: -fwarn-unused-imports -fno-warn-warnings-deprecations
    dependencies:
    - base
    - aeson
    - amqp
    - bson
    - bson-generic
    - bytestring
    - case-insensitive
    - containers
    - data-default
    - ginger
    - http-client
    - http-types
    - lens
    - jwt
    - mtl
    - monad-control
    - monad-logger
    - mongoDB
    - network
    - persistent
    - persistent-template
    - persistent-mongoDB
    - pretty-simple
    - pwstore-fast
    - random
    - regex-compat
    - roman-numerals
    - scotty
    - text
    - time
    - transformers
    - unordered-containers
    - uuid
    - vector
    - wai
    - wai-extra
    - wai-cors
    - warp
    - yaml
    - dsw-server
    - hspec
    - hspec-expectations-pretty-diff
    - hspec-wai
    - hspec-wai-json
    default-extensions:
      - TemplateHaskell
      - QuasiQuotes
      - OverloadedStrings
      - MultiParamTypeClasses
      - FlexibleContexts
      - GeneralizedNewtypeDeriving
      - GADTs
      - TypeFamilies
      - DeriveGeneric
      - ExtendedDefaultRules
      - RecordWildCards
      - UnicodeSyntax
      - ExistentialQuantification
      - FunctionalDependencies
      - TypeSynonymInstances
      - FlexibleInstances
